tasks:
  - name : kind
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
       curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64"
       chmod +x ./kind
       sudo mv ./kind /usr/local/bin/kind
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - cweijan.vscode-postgresql-client2
