tasks:
  - name : kind
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |	
       sudo usermod -aG docker $USER
       curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
       sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
       curl -LO "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
       sudo dpkg -i minikube_latest_amd64.deb
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
